name: Build w/ Makefile

on:
  push:
    branches:
    - trunk
  pull_request:
    branches:
    - trunk

  schedule:
  - cron: "0 2 * * 5"
  

jobs:
  build:
    name: deploy to staging
    runs-on:
    - ubuntu-latest
    - macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang libncurses5-dev libx11-dev

    - name: Build with Makefile
      run: make all

    - name: Test echo cmd
      run: ./echo Hello, World!

    - name: Test open/close shell
      run: |
        ./app
        ❌
      
