name: Build w/ Ninja

on:
  push:
    branches:
    - trunk
  pull_request:
    branches:
    - trunk
  schedule:
  - cron: "0 2 * * 5"
  

jobs:
  Build-On-Linux:
    name: Build hrry on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang libx11-dev ninja-build

    - name: Configure with CMake (using build_tools)
      run: ./build_tools/build_with_ninja.sh

    - name: Test open/close shell
      run: |
        echo "❌" | ./hrry 
    - name: Test open ls(👀) and then exit
      run : |
        echo -e "👀\n❌" > cmd.sh && chmod +x cmd.sh  && ./hrry < cmd.sh

  Build-On-Mac:
    name: Build hrry on Mac
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: brew update && brew install libx11 ninja

    - name: Configure with CMake (using build_tools)
      run: ./build_tools/build_with_ninja.sh
      
    - name: Test open/close shell
      run: |
        echo "❌" | ./hrry 
  
    - name: Test open ls(👀) and then exit
      run : |
        echo -e "👀\n❌" > cmd.sh && chmod +x cmd.sh  && ./hrry < cmd.sh
